# Generated by Django 5.0.7 on 2024-07-22 10:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=60)),
                ('car_brand', models.TextField(max_length=200)),
                ('car_price', models.PositiveIntegerField()),
                ('is_bought', models.BooleanField()),
                ('buy_time', models.DateTimeField(default=datetime.datetime(2024, 7, 22, 10, 14, 2, 739823, tzinfo=datetime.timezone.utc))),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
