# Generated by Django 5.0.7 on 2024-07-22 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='buy_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 10, 17, 19, 507360, tzinfo=datetime.timezone.utc)),
        ),
    ]
